language: php
sudo: false
matrix:
  include:
  - php: 7.1
  - php: 5.6
  - php: 5.4
env:
  global:
  - WP_VERSION=master WP_MULTISITE=0
  - secure: WYH4JaFh+qKyBlrwVf6irhrYLJ7RSXXJqiElQAwXz1FbdB7njDM/qGlvGdH0uvM0xUEaHEiMl7qs4F5W9H9yjRkK9Vp4mfR9UkWWCmPP1JslW5/scpxyg8+lYwFXmNmqLW69xVqQgQDJFab5Dn/Jpct/oF7ijBiYHl0eopNnDrGDB956JtLLiHmQe3Rqi6zaPzR8/a0Xv0NGSi2nOMrkIZlkg5h9J5ZT6lssrNmgUvFqW1sr85LBWguW+L8BkGPly55UpxheAt2NQ3G2KYKsAU68uBcO6sQUezV3RdSJ1ShyrP+OgMKK55n/VV9BOMcy+ZUL4q4os6YhmzFdv/ySnn3azKEHuBuaiVF5aEcgPzPgeQqVYFC7G3gZirrZyFQ7fthX9MOmKHtT4KMLh7sZk8monWODz0Bct8MJGZrF43OyaBwpFqwpHA9AW5bkZxURgEGWs8UtK6JbXcgV2oYc4HyTXfnqDgywXAI9y+A8WmiIvlmTL7rQqzqbWJvN2e7T2gpXsg0BmKqIt/K1sR5KZoh9B1pwMAAfVc2ip6Ibduu5NvvyFE+PdlwFrprD8RFg9aihrDkPDXK0flAxqVKgsx0yJq8jvjWpn5F3+pcsNuQKpMQZPzZ8R+09JynvIiikCiZ8L9IGVR0zJ6lzTiyeMw/erBwNaYtPpAss9mt7rxg=
notifications:
  slack:
    secure: U0C7obTxqgI1blt1RIhIY+M3mU94CgSVMCP3oWtPyVaXrDwYdlSZvqXGCdezJXqVzFOcMEytDlKMJxo1zM6fnXlpqvUllBGm2IJkpQj6ijUr+uQy6bVqMWQiIWDho8XRKH3GoYa812XSsNJOROX+let9JiXiO5qz0DWSs3FQ4gl+Ti+E/Znck9yE32AfY5rHEhtkbN2ih/Agx7o+8PkdGG2BGr6hqfn/Gf1sHiUA6KifdoD6lZRR/nym/1osEMlkuavbY4tOf+RBvUTpSpyBDthPXmgXCPJZ8iGGTKySic7KF367AXITWNWdZxX0ChzNB6WcmJWvdvghbxRnIZXN3nML+gtXclmNnH8GOO4iLyXtUbyh7JpoZh/5KVnqP2hmgjPzBGNm84JBmZuqB7jIKHAZwWh66u9k03uteM5wrYNxQBYvDHvTaeeP7TnOBDWhUkjvEacx61TpxmUCb6VGHahSv/MuqaAEpvolcj83BPBC4fjrLA3dj6u+WjYxTqRZeA9A35eW6qT3182beKHCj+GfN1PfsMRGCyqebxcj6CMLgGti0UMgFUBBp1w30z54vKq/lpIRCgMYXQWbETJPLhez76u9MqVCc1j9JoxD6o7we3BsvYtOhngnCbKLcpDzsQK8q/TTtVB/etfQcYdir6lkJn4wAQbvoM5US8uPQ7w=
before_script:
- nvm install 10.13.0
- nvm use 10.13.0
- npm install --global gulp-cli
- yarn install && yarn run build
- export WP_DEVELOP_DIR=/tmp/wordpress/
- mkdir -p $WP_DEVELOP_DIR
- git clone --depth=1 --branch="$WP_VERSION" git://develop.git.wordpress.org/ $WP_DEVELOP_DIR
- framework_dir=$(basename $(pwd))/boldgrid-theme-framework
- theme_dir=$WP_DEVELOP_DIR/src/wp-content/themes/prime
- cd ..
- git clone -b dev https://github.com/boldgrid/prime $theme_dir
- cp -r $framework_dir/. $theme_dir/inc/boldgrid-theme-framework
- cd $WP_DEVELOP_DIR
- echo $WP_DEVELOP_DIR
- cp wp-tests-config-sample.php wp-tests-config.php
- sed -i "s/youremptytestdbnamehere/wordpress_test/" wp-tests-config.php
- sed -i "s/yourusernamehere/root/" wp-tests-config.php
- sed -i "s/yourpasswordhere//" wp-tests-config.php
- mysql -e 'CREATE DATABASE wordpress_test;' -uroot
- mkdir php-codesniffer && curl -L https://github.com/squizlabs/PHP_CodeSniffer/archive/2.9.tar.gz | tar xz --strip-components=1 -C php-codesniffer
- mkdir wordpress-coding-standards && curl -L https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/archive/0.10.0.tar.gz | tar xz --strip-components=1 -C wordpress-coding-standards
- cd php-codesniffer
- scripts/phpcs --config-set installed_paths ../wordpress-coding-standards
- cd $theme_dir
- phpenv rehash
script:
- find . \( -name '*.php' \) -exec php -lf {} \;
- "$WP_DEVELOP_DIR/php-codesniffer/scripts/phpcs -p -s -v -n . --standard=$TRAVIS_BUILD_DIR/phpcs.ruleset.xml --ignore=*partials/hover-colors-only.php,*/scssphp/*,*/kirki/*,*/wp_bootstrap_navwalker.php,*/class-boldgrid-framework-pointer.php,*/woocommerce/* --extensions=php"
deploy:
- provider: script
  script: node $TRAVIS_BUILD_DIR/build/build-zip.js
  skip_cleanup: true
  on:
    tags: true
    php: '7.1'
- provider: releases
  api_key:
    secure: ILkTznHjXK2hvc7v5OPZsHtDM8UCSk3qJUGA3lGqoUGmCCpHMRjay9JGm1VyNxlj+UmHBfFbukPm6bRUzg7Y0XeMpzfYTuiYAWIzFHsAMgFO56PdP1YCCa9rDwqOE//K+ED6PQz4r6wSPqLegjdhzQ3DJM+1nUkdcuwvkBNVfhSTDbryw7X1TQ6jOadBSPleG2PwdPOT19RU6hUMVJneLHLLi6jWZNonclvxFupornBoldzHPuT+l8Pu41nPpxEJsW1MoZifbdFR77kJrQERV51OOU6RPB8V3ADNDjeSuMss7uIVedJAkwqbzuFHAj2umIdEiAhfOfyi4NpNnwEfECz633eHVZH+cfEMpeWSvZbd1Eh3Jm+LdBmMq2DkNss3XwJg5op71Ac3DJ8yDbxRplFCsOJ8MS4ky8d9DeReTwgyimp0oXD7uGAL8RIfPf8rlwsD+aQn80LsYYkMMWTfTAAy1gM29nUcbSuBWIe1bkJP9QSI2MQJ5ViAO2zHHHdut5c7jVj82wUAjlmOKYx529JcXfMsrQTTKPat0e3Ks224yfoYZSMyw0by3okAYskq5kx9L3ib+QJO6LwzMUTjgUtn4lLzdFOVC9fysb6h8ULCbOg0fnAlyWMmP+p+4RiV8BXbdekXJZkuLrm0vVMBEuXQ7lf/zW56EmlGIgmwXiU=
  file: bgtfw.zip
  on:
    repo: BoldGrid/boldgrid-theme-framework
    tags: true
    php: '7.1'
- provider: script
  script: node $TRAVIS_BUILD_DIR/build/remote-update.js
  on:
    tags: true
    php: '7.1'
